/* The following code was generated by JFlex 1.4_pre3 on 02/05/2022, 22:25 */


   
/* --------------------------Usercode Section------------------------ */
package src;
import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4_pre3
 * on 02/05/2022, 22:25 from the specification file
 * <tt>file:/C:/Users/mmueller43/AIT/PLC-Compiler/src/flex/voc_flex.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int YY_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  2,  0,  3,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     9, 45,  0, 10, 10, 26, 42,  7, 27, 28, 24, 22, 21, 23,  4, 25, 
     5,  6,  6,  6,  6,  6,  6,  6,  6,  6, 48, 20, 43, 29, 44,  0, 
    10,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 
     8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  0,  0,  0, 10, 11, 
     0, 17, 39, 47, 32, 15, 16, 40, 35, 30,  8,  8, 18,  8, 31, 36, 
    33,  8, 13, 19, 12, 14, 46, 34,  8,  8,  8, 37, 41, 38,  0,  0
  };


  /** 
   * Translates a state to a row index in the transition table (packed version)
   */
  final private static String yy_rowMap_packed = 
    "\0\0\0\61\0\142\0\61\0\223\0\304\0\365\0\u0126\0\u0157\0\u0188"+
    "\0\u01b9\0\u01ea\0\u021b\0\u024c\0\61\0\61\0\61\0\61\0\61\0\61"+
    "\0\61\0\61\0\61\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\61\0\61"+
    "\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\61\0\u04c9\0\223"+
    "\0\u04fa\0\61\0\365\0\u052b\0\u055c\0\u058d\0\u05be\0\u05ef\0\u0620\0\u0651"+
    "\0\u0682\0\u06b3\0\u06e4\0\u0715\0\61\0\u0126\0\u0746\0\u0126\0\u0777\0\u07a8"+
    "\0\u07d9\0\61\0\61\0\61\0\61\0\61\0\u080a\0\u04c9\0\u083b\0\u086c"+
    "\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u0126\0\u09c3\0\u0126\0\u09f4"+
    "\0\u0a25\0\u0a56\0\u0a87\0\u0126\0\u0ab8\0\u0ae9\0\u0126\0\u0b1a\0\u0126\0\u0b4b"+
    "\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0126\0\u0c40\0\u0126\0\u0126\0\u0126\0\u0c71"+
    "\0\u0126\0\u0126\0\u0ca2\0\u0126\0\u0126\0\u0cd3\0\u0126";

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int [] yy_rowMap = yy_unpack_rowMap(yy_rowMap_packed);


  /** 
   * Unpacks the compressed row translation table.
   *
   * @param packed   the packed row translation table
   * @return         the unpacked row translation table
   */
  private static int [] yy_unpack_rowMap(String packed) {
    int [] map = new int[214];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 214) {
      int high = ((int) packed.charAt(i++)) << 16;
      map[j++] = high | packed.charAt(i++);
    }
    return map;
  }
  /** 
   * The packed transition table of the DFA (part 0)
   */
  private static final String yy_packed0 = 
    "\1\2\1\3\2\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\4\1\2\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\10\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\10\1\32\1\33"+
    "\1\34\2\10\1\35\1\36\1\37\1\10\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\10\1\46\63\0\1\4"+
    "\62\0\1\47\2\50\56\0\1\47\2\6\57\0\2\51"+
    "\1\52\2\53\1\54\1\0\10\53\4\0\1\54\1\0"+
    "\3\54\1\0\7\53\2\0\2\53\2\54\2\0\1\54"+
    "\2\53\6\0\2\10\1\0\1\10\2\0\11\10\12\0"+
    "\7\10\2\0\2\10\5\0\2\10\6\0\2\10\1\0"+
    "\1\10\2\0\2\10\1\55\6\10\12\0\7\10\2\0"+
    "\2\10\5\0\2\10\6\0\2\10\1\0\1\10\2\0"+
    "\4\10\1\56\4\10\12\0\7\10\2\0\2\10\5\0"+
    "\2\10\6\0\2\10\1\0\1\10\2\0\11\10\12\0"+
    "\1\10\1\57\5\10\2\0\2\10\5\0\2\10\6\0"+
    "\2\10\1\0\1\10\2\0\7\10\1\60\1\10\12\0"+
    "\1\10\1\61\5\10\2\0\2\10\5\0\2\10\6\0"+
    "\2\10\1\0\1\10\2\0\3\10\1\62\2\10\1\63"+
    "\1\64\1\10\12\0\6\10\1\65\2\0\2\10\5\0"+
    "\2\10\6\0\2\10\1\0\1\10\2\0\1\10\1\66"+
    "\7\10\12\0\7\10\2\0\2\10\5\0\2\10\36\0"+
    "\1\67\30\0\2\10\1\0\1\10\2\0\5\10\1\70"+
    "\3\10\12\0\1\10\1\71\5\10\2\0\2\10\5\0"+
    "\2\10\6\0\2\10\1\0\1\10\2\0\11\10\12\0"+
    "\6\10\1\72\2\0\2\10\5\0\2\10\6\0\2\10"+
    "\1\0\1\10\2\0\2\10\1\73\6\10\12\0\7\10"+
    "\2\0\2\10\5\0\2\10\6\0\2\10\1\0\1\10"+
    "\2\0\11\10\12\0\5\10\1\74\1\10\2\0\2\10"+
    "\5\0\2\10\6\0\2\10\1\0\1\10\2\0\11\10"+
    "\12\0\6\10\1\75\2\0\2\10\5\0\2\10\52\0"+
    "\1\76\61\0\1\77\43\0\1\100\60\0\1\101\60\0"+
    "\1\102\30\0\2\10\1\0\1\10\2\0\11\10\12\0"+
    "\6\10\1\103\2\0\2\10\5\0\2\10\6\0\2\104"+
    "\57\0\2\51\1\52\56\0\2\51\1\52\2\0\1\54"+
    "\15\0\1\54\1\0\3\54\14\0\2\54\2\0\1\54"+
    "\10\0\2\10\1\0\1\10\2\0\3\10\1\105\5\10"+
    "\12\0\7\10\2\0\2\10\5\0\2\10\6\0\2\10"+
    "\1\0\1\10\2\0\1\10\1\106\7\10\12\0\7\10"+
    "\2\0\2\10\5\0\2\10\6\0\2\10\1\0\1\10"+
    "\2\0\1\10\1\107\7\10\12\0\7\10\2\0\2\10"+
    "\5\0\2\10\6\0\2\10\1\0\1\10\2\0\10\10"+
    "\1\110\12\0\7\10\2\0\2\10\5\0\2\10\6\0"+
    "\2\10\1\0\1\10\2\0\11\10\12\0\2\10\1\111"+
    "\4\10\2\0\2\10\5\0\2\10\6\0\2\10\1\0"+
    "\1\10\2\0\11\10\12\0\1\10\1\112\5\10\2\0"+
    "\2\10\5\0\2\10\6\0\2\10\1\0\1\10\2\0"+
    "\7\10\1\113\1\10\12\0\7\10\2\0\2\10\5\0"+
    "\2\10\6\0\2\10\1\0\1\10\2\0\11\10\12\0"+
    "\6\10\1\114\2\0\2\10\5\0\2\10\6\0\2\10"+
    "\1\0\1\10\2\0\2\10\1\115\6\10\12\0\7\10"+
    "\2\0\2\10\5\0\2\10\6\0\2\10\1\0\1\10"+
    "\2\0\2\10\1\116\6\10\12\0\7\10\2\0\2\10"+
    "\5\0\2\10\6\0\2\10\1\0\1\10\2\0\1\10"+
    "\1\117\7\10\12\0\7\10\2\0\2\10\5\0\2\10"+
    "\6\0\2\10\1\0\1\10\2\0\11\10\12\0\1\120"+
    "\6\10\2\0\2\10\5\0\2\10\6\0\2\10\1\0"+
    "\1\10\2\0\11\10\12\0\1\121\6\10\2\0\2\10"+
    "\5\0\2\10\6\0\2\10\1\0\1\10\2\0\11\10"+
    "\12\0\6\10\1\122\2\0\2\10\5\0\2\10\6\0"+
    "\2\10\1\0\1\10\2\0\11\10\12\0\1\123\6\10"+
    "\2\0\2\10\5\0\2\10\6\0\2\10\1\0\1\10"+
    "\2\0\4\10\1\124\4\10\12\0\7\10\2\0\2\10"+
    "\5\0\2\10\6\0\2\10\1\0\1\10\2\0\3\10"+
    "\1\125\5\10\12\0\7\10\2\0\2\10\5\0\2\10"+
    "\6\0\2\10\1\0\1\10\2\0\11\10\12\0\1\126"+
    "\6\10\2\0\2\10\5\0\2\10\6\0\2\10\1\0"+
    "\1\10\2\0\4\10\1\127\4\10\12\0\7\10\2\0"+
    "\2\10\5\0\2\10\6\0\2\10\1\0\1\10\2\0"+
    "\11\10\12\0\1\130\6\10\2\0\2\10\5\0\2\10"+
    "\6\0\2\10\1\0\1\10\2\0\11\10\12\0\7\10"+
    "\2\0\2\10\5\0\1\10\1\131\6\0\2\10\1\0"+
    "\1\10\2\0\10\10\1\105\12\0\7\10\2\0\2\10"+
    "\5\0\2\10\6\0\2\10\1\0\1\10\2\0\6\10"+
    "\1\132\2\10\12\0\7\10\2\0\2\10\5\0\2\10"+
    "\6\0\2\10\1\0\1\10\2\0\11\10\12\0\1\133"+
    "\6\10\2\0\2\10\5\0\2\10\6\0\2\10\1\0"+
    "\1\10\2\0\11\10\12\0\1\10\1\134\5\10\2\0"+
    "\2\10\5\0\2\10\6\0\2\10\1\0\1\10\2\0"+
    "\7\10\1\135\1\10\12\0\7\10\2\0\2\10\5\0"+
    "\2\10\6\0\2\10\1\0\1\10\2\0\7\10\1\136"+
    "\1\10\12\0\7\10\2\0\2\10\5\0\2\10\6\0"+
    "\2\10\1\0\1\10\2\0\11\10\12\0\2\10\1\137"+
    "\4\10\2\0\2\10\5\0\2\10\6\0\2\10\1\0"+
    "\1\10\2\0\2\10\1\140\6\10\12\0\7\10\2\0"+
    "\2\10\5\0\2\10\6\0\2\10\1\0\1\10\2\0"+
    "\7\10\1\141\1\10\12\0\7\10\2\0\2\10\5\0"+
    "\2\10\6\0\2\10\1\0\1\10\2\0\5\10\1\142"+
    "\3\10\12\0\7\10\2\0\2\10\5\0\2\10\6\0"+
    "\2\10\1\0\1\10\2\0\1\10\1\143\7\10\12\0"+
    "\7\10\2\0\2\10\5\0\2\10\6\0\2\10\1\0"+
    "\1\10\2\0\11\10\12\0\1\10\1\144\5\10\2\0"+
    "\2\10\5\0\2\10\6\0\2\10\1\0\1\10\2\0"+
    "\1\10\1\145\7\10\12\0\7\10\2\0\2\10\5\0"+
    "\2\10\6\0\2\10\1\0\1\10\2\0\4\10\1\146"+
    "\4\10\12\0\7\10\2\0\2\10\5\0\2\10\6\0"+
    "\2\10\1\0\1\10\2\0\4\10\1\147\4\10\12\0"+
    "\7\10\2\0\2\10\5\0\2\10\6\0\2\10\1\0"+
    "\1\10\2\0\11\10\12\0\1\10\1\150\5\10\2\0"+
    "\2\10\5\0\2\10\6\0\2\10\1\0\1\10\2\0"+
    "\11\10\12\0\7\10\2\0\1\10\1\151\5\0\2\10"+
    "\6\0\2\10\1\0\1\10\2\0\6\10\1\152\2\10"+
    "\12\0\7\10\2\0\2\10\5\0\2\10\6\0\2\10"+
    "\1\0\1\10\2\0\11\10\12\0\1\10\1\153\5\10"+
    "\2\0\2\10\5\0\2\10\1\0";

  /** 
   * The transition table of the DFA
   */
  private static final int yytrans [] = yy_unpack();


  /* error codes */
  private static final int YY_UNKNOWN_ERROR = 0;
  private static final int YY_ILLEGAL_STATE = 1;
  private static final int YY_NO_MATCH = 2;
  private static final int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  private static final String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final byte YY_ATTRIBUTE[] = {
     0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9, 
     9,  9,  9,  9,  9,  9,  9,  1,  1,  1,  1,  1,  9,  9,  1,  1, 
     1,  1,  1,  1,  1,  9,  0,  0,  0,  9,  0,  0,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  9,  9,  9, 
     9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3332];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 4: 
        case 5: 
          { return symbol(sym.INTEGER_LITERAL, new Integer(yytext())); }
        case 108: break;
        case 67: 
          { return symbol(sym.FLOAT_LITERAL, new Float(yytext())); }
        case 109: break;
        case 22: 
          {  return symbol(sym.RPAREN);  }
        case 110: break;
        case 21: 
          {  return symbol(sym.LPAREN);  }
        case 111: break;
        case 19: 
          {  return symbol(sym.DIVIDE);  }
        case 112: break;
        case 65: 
          {  return symbol (sym.NOTEQUAL); }
        case 113: break;
        case 104: 
          {  return symbol (sym.STRING); }
        case 114: break;
        case 103: 
          {  return symbol  (sym.RETURN); }
        case 115: break;
        case 2: 
        case 3: 
          {  /* just skip what was found, do nothing */  }
        case 116: break;
        case 37: 
          {  return symbol  (sym.COLON); }
        case 117: break;
        case 86: 
          { return symbol(sym.ELSE);   }
        case 118: break;
        case 33: 
          {  return symbol (sym.LT); }
        case 119: break;
        case 29: 
          {  return symbol(sym.END);  }
        case 120: break;
        case 23: 
          {  return symbol(sym.EQ);  }
        case 121: break;
        case 20: 
          {  return symbol(sym.MOD);  }
        case 122: break;
        case 34: 
          {  return symbol (sym.GT); }
        case 123: break;
        case 55: 
          {  return symbol(sym.IF);  }
        case 124: break;
        case 57: 
          {  return symbol(sym.DO);  }
        case 125: break;
        case 61: 
          {  return symbol (sym.OR); }
        case 126: break;
        case 62: 
          {  return symbol (sym.AND); }
        case 127: break;
        case 63: 
          {  return symbol (sym.LTE); }
        case 128: break;
        case 64: 
          {  return symbol (sym.GTE); }
        case 129: break;
        case 76: 
          {  return symbol(sym.FOR);  }
        case 130: break;
        case 78: 
          {  return symbol (sym.INT); }
        case 131: break;
        case 106: 
          {  return symbol (sym.BOOL); }
        case 132: break;
        case 101: 
          {  return symbol(sym.WHILE);  }
        case 133: break;
        case 100: 
          {  return symbol(sym.PRINT);  }
        case 134: break;
        case 98: 
          {  return symbol (sym.FLOAT); }
        case 135: break;
        case 96: 
          {  return symbol(sym.UNTIL);  }
        case 136: break;
        case 7: 
        case 8: 
        case 9: 
        case 10: 
        case 11: 
        case 12: 
        case 13: 
        case 24: 
        case 25: 
        case 26: 
        case 27: 
        case 30: 
        case 36: 
        case 44: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 56: 
        case 58: 
        case 59: 
        case 60: 
        case 66: 
        case 68: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 77: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 84: 
        case 85: 
        case 87: 
        case 89: 
        case 90: 
        case 91: 
        case 92: 
        case 93: 
        case 95: 
        case 99: 
        case 102: 
        case 105: 
          { 
                        Integer n = (Integer) SymbolTable.globalTable.get(yytext());

                        if (n == null) {
                               SymbolTable.globalTable.put(yytext(),0);
                        }
                        return symbol(sym.ID, yytext());
                        }
        case 137: break;
        case 28: 
          {  return symbol(sym.BEGIN);  }
        case 138: break;
        case 18: 
          {  return symbol(sym.TIMES);  }
        case 139: break;
        case 14: 
          {  return symbol(sym.SEMI);  }
        case 140: break;
        case 15: 
          {  return symbol(sym.COMMA);  }
        case 141: break;
        case 16: 
          {  return symbol(sym.PLUS);  }
        case 142: break;
        case 17: 
          {  return symbol(sym.MINUS);  }
        case 143: break;
        case 54: 
          {  return symbol (sym.EQUAL); }
        case 144: break;
        case 88: 
          {  return symbol  (sym.FUNC); }
        case 145: break;
        case 94: 
          {  return symbol  (sym.VOID); }
        case 146: break;
        case 1: 
        case 6: 
        case 31: 
        case 32: 
        case 35: 
          {  throw new Error("Illegal character <"+yytext()+">");  }
        case 147: break;
        case 41: 
          { return symbol(sym.STRING_LITERAL,new String (yytext().substring(1,yylength()-1))); }
        case 148: break;
        case 83: 
          { return symbol(sym.BOL,new Boolean(yytext())); }
        case 149: break;
        case 97: 
          { return symbol(sym.ENDIF); }
        case 150: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
