
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 30 20:35:45 ICT 2022
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 7;
  public static final int STRING_LITERAL = 40;
  public static final int LTE = 31;
  public static final int NOTEQUAL = 33;
  public static final int LPAREN = 9;
  public static final int SEMI = 2;
  public static final int INT = 22;
  public static final int FOR = 17;
  public static final int MINUS = 5;
  public static final int RPAREN = 10;
  public static final int AND = 28;
  public static final int LT = 27;
  public static final int OR = 26;
  public static final int BOOL = 24;
  public static final int COMMA = 3;
  public static final int BEGIN = 20;
  public static final int UNTIL = 19;
  public static final int PLUS = 4;
  public static final int IF = 12;
  public static final int ID = 39;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int EQUAL = 32;
  public static final int error = 1;
  public static final int MOD = 8;
  public static final int VOID = 34;
  public static final int EQ = 11;
  public static final int GTE = 30;
  public static final int TIMES = 6;
  public static final int ENDIF = 14;
  public static final int ELSE = 13;
  public static final int WHILE = 16;
  public static final int BOL = 36;
  public static final int FLOAT = 23;
  public static final int END = 21;
  public static final int STRING = 25;
  public static final int FLOAT_LITERAL = 38;
  public static final int GT = 29;
  public static final int PRINT = 15;
  public static final int DO = 18;
  public static final int INTEGER_LITERAL = 37;
}

